server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rohit23
    driver-class-name: org.postgresql.Driver

logging.level.org.hibernate.SQL: debug  
  